# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: '⟩ MSGdec_STATUS::E_DONE<br>⟩ _Transmission checksum 383789300…<img src="https://flowaria.github.io/GTFO-HangulPatch/images/cursor.gif" style="height: 1em;vertical-align: text-bottom;" width="8">'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
